### ISSUE TITLE
Unable to find any child-parent relationship for the child type

### ISSUE THREAD

**Issue by rsr-maersk** [MoonStorm/FastCrud#181]
Hi
Tanks for the coolio package

Unable to find any child-parent relationship for the child type analyzing the navigation property 'Users' on the parent entity. 

What to do when i don't want the child items, i just want the parent flat without relationships?

THis doesn't seam to be working:
`
await db.GetAsync(new Foo { Id = id }, options =>
        {           options.WithEntityMappingOverride(OrmConfiguration.GetDefaultEntityMapping<Foo>().Clone().RemoveAllRelationships().RemoveProperty(x => x.Bar));
        });
`

The original migration / model is from EF Core many to many.

Unable to find any child-parent relationship for the child type 'Bar' and the parent 'USer' when analyzing the navigation property 'Users' on the parent entity.

even tried with 
.RemoveParentChildRelationship(x => x.Bar),
RemoveParentChildrenRelationship(x => x.Bar),
.RemoveChildParentRelationship(x => x.Bar),

**Comment by slipjig** [comment]
I am getting this error as well, using fluent registration.  Here is a simple example to duplicate the issue:

public class Parent {
    public long Key { get; set; }
    public IEnumerable<Child> Children { get; set; }
}

public class Child {
    public long Key { get; set; }
    public long ParentKey { get; set; }
    public Parent Parent { get; set; }
}

public class Config {
    private static void ConfigureParentsAndChildren() {
        OrmConfiguration.GetDefaultEntityMapping<Parent>()
            .SetDialect(SqlDialect.MySql)
            .SetTableName("parents")

            .SetProperty(p => p.Key, p => p
                .SetDatabaseColumnName("parent_id")
                .SetPrimaryKey()
                .SetDatabaseGenerated(DatabaseGeneratedOption.Identity))

            .SetParentChildrenRelationship(                         //<-------- FAILS
                p => p.Children,
                c => c.Parent
            );

        OrmConfiguration.GetDefaultEntityMapping<Child>()
            .SetDialect(SqlDialect.MySql)
            .SetTableName("children")

            .SetProperty(p => p.Key, p => p
                .SetDatabaseColumnName("child_id")
                .SetPrimaryKey()
                .SetDatabaseGenerated(DatabaseGeneratedOption.Identity))

            .SetChildParentRelationship(
                c => c.Parent,
                c => c.ParentKey
            );
    }
}

Is this supposed to work the way I've written it?

**Comment by slipjig** [comment]
In my example above, if I change it to use .RegisterEntity<T>() instead of .GetDefaultEntityMapping<T>(), it runs.

**Comment by wishmaster-** [comment]
Hi there
I don't really understand the exception I receive on trying to update an entity.
This is the exception:
`System.InvalidOperationException: Unable to find any child-parent relationship for the child type '<path>.CustomerUser' and the parent '<samepath>.Customer' when analyzing the navigation property 'AuthorizedUsers' on the parent entity.
   at Dapper.FastCrud.Mappings.AutoGeneratedEntityMapping`1.DiscoverParentChildrenRelationships(Type entityType)+MoveNext() in D:\a\1\s\Dapper.FastCrud\Mappings\AutoGeneratedEntityMapping.cs:line 180
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Dapper.FastCrud.Mappings.AutoGeneratedEntityMapping`1.DiscoverEntityMapping() in D:\a\1\s\Dapper.FastCrud\Mappings\AutoGeneratedEntityMapping.cs:line 53
   at System.Lazy`1.CreateValue()
   at Dapper.FastCrud.Mappings.AutoGeneratedEntityMapping`1.get_AutoGeneratedRegistration() in D:\a\1\s\Dapper.FastCrud\Mappings\AutoGeneratedEntityMapping.cs:line 31
   at Dapper.FastCrud.EntityDescriptors.EntityDescriptor`1.<>c.<.ctor>b__1_0() in D:\a\1\s\Dapper.FastCrud\EntityDescriptors\EntityDescriptor(TEntity).cs:line 25
   at System.Lazy`1.CreateValue()
   at Dapper.FastCrud.Configuration.StatementOptions.Aggregated.AggregatedSqlStatementOptions.get_EntityRegistration() in D:\a\1\s\Dapper.FastCrud\Configuration\StatementOptions\Aggregated\AggregatedSqlStatementOptions.cs:line 65
   at Dapper.FastCrud.Configuration.StatementOptions.Builders.Aggregated.AggregatedSqlStatementOptionsBuilder`2..ctor() in D:\a\1\s\Dapper.FastCrud\Configuration\StatementOptions\Builders\Aggregated\AggregatedSqlStatementOptionsBuilder.cs:line 24
   at Dapper.FastCrud.Configuration.StatementOptions.Builders.StandardSqlStatementOptionsBuilder`1..ctor()
   at Dapper.FastCrud.DapperExtensions.UpdateAsync[TEntity](IDbConnection connection, TEntity entityToUpdate, Action`1 statementOptions) in D:\a\1\s\Dapper.FastCrud\DapperExtensions.cs:line 124
   at Project.Infrastructure.DapperDbContext.UpdateAsync[T](T entity) in C:\source\repos\Project\Project\Infrastructure\DapperDbConnection.cs:line 76
   at Project.Repositories.Repository.UpdateCustomer(Customer customer) in C:\source\repos\Project\Project\Repositories\Repository.cs:line 378
   at Project2.Hangfire.Jobs.StatusJob.RunAsync(Int32 customerId, PerformContext performContext, Dictionary`2 parameters, Boolean force) in C:\source\repos\Project\Project2\Hangfire\Jobs\Job.cs:line 115
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)`


I'm using this method to update:

![image](https://github.com/MoonStorm/FastCrud/assets/7646231/e31617b2-655f-494d-8e6b-b2468eb41e24)

The models look like this:

` public class Customer
{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<CustomerUser> AuthorizedUsers { get; set; } = new List<CustomerUser>();
}

public class CustomerUser
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public int CustomerId { get; set; }
}`

I am using FastCrud 3.1.46 and also AutoMapper, but since this is all from FastCrud I don't think that matters?
Dapper 2.1.28 and Dapper.Contrib 2.0.78

What is wrong here?
I don't have such a OrmConfiguration thing, we have Migrations done with FluentMigrator
One of which sets the ForeignKey property for the CustomerUser UserId

**Comment by MoonStorm** [comment]
> In my example above, if I change it to use .RegisterEntity() instead of .GetDefaultEntityMapping(), it runs.

RegisterEntity should be the right way when performing fluent registrations from scratch, as GetDefaultEntityMapping will make inferations that need to be overridden. Let me know if you do encounter any more problems in this area.
