### ISSUE TITLE
sequence contains no elements

### ISSUE THREAD

**Issue by anhlunnhaque** [MoonStorm/FastCrud#50]
Hello,

I've encounter a 'sequence contains no elements' exception when trying to Update an entity. Any help would be appreciated.
`using (var connection = GetOpenConnection())
            {
                connection.Update(hmsJobEntity);
            }`

`public class HmsJob
    {
[System.ComponentModel.DataAnnotations.Key]       
        public int Id { get; set; }
        public string Name { get; set; }
public virtual ICollection<HmsJobSetting> HmsJobSetting { get; set; }

}`

`public partial class HmsJobSetting
    {
        [System.ComponentModel.DataAnnotations.Key]       
        public int Id { get; set; }

        [System.ComponentModel.DataAnnotations.Schema.ForeignKey("HmsJob")]
        public int HmsJobId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string Comments { get; set; }
        
        public virtual HmsJob HmsJob { get; set; }
    }`

**Comment by MoonStorm** [comment]
Could you paste the section of the stack trace which relates to FastCrud? Thanks.

**Comment by anhlunnhaque** [comment]
Here you go:

at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at Dapper.FastCrud.Mappings.EntityMapping.FreezeMapping()
   at Dapper.FastCrud.EntityDescriptors.EntityDescriptor`1.ConstructSqlStatements(EntityMapping entityMapping)
   at Dapper.FastCrud.EntityDescriptors.EntityDescriptor`1.<.ctor>b__2_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Dapper.FastCrud.EntityDescriptors.EntityDescriptor`1.GetSqlStatements(EntityMapping entityMapping)
   at Dapper.FastCrud.OrmConfiguration.GetSqlStatements[TEntity](EntityMapping entityMapping)
   at Dapper.FastCrud.Configuration.StatementOptions.Aggregated.AggregatedSqlStatementOptions`1.<.ctor>b__0_0()
   at Dapper.FastCrud.DapperExtensions.Update[TEntity](IDbConnection connection, TEntity entityToUpdate, Action`1 statementOptions)

**Comment by kipusoep** [comment]
Having the same issue with a delete call:

```
{
	"Message": "An error has occurred.",
	"ExceptionMessage": "Sequence contains no elements",
	"ExceptionType": "System.InvalidOperationException",
	"StackTrace": "   at System.Linq.Enumerable.Max(IEnumerable`1 source)
	   at Dapper.FastCrud.Mappings.EntityMapping.FreezeMapping()
	   at Dapper.FastCrud.EntityDescriptors.EntityDescriptor`1.ConstructSqlStatements(EntityMapping entityMapping)
	   at Dapper.FastCrud.EntityDescriptors.EntityDescriptor`1.<.ctor>b__2_0()
	   at System.Lazy`1.CreateValue()
	   at System.Lazy`1.LazyInitValue()
	   at System.Lazy`1.get_Value()
	   at Dapper.FastCrud.EntityDescriptors.EntityDescriptor`1.GetSqlStatements(EntityMapping entityMapping)
	   at Dapper.FastCrud.OrmConfiguration.GetSqlStatements[TEntity](EntityMapping entityMapping)
	   at Dapper.FastCrud.Configuration.StatementOptions.Aggregated.AggregatedSqlStatementOptions`1.<.ctor>b__0_0()
	   at Dapper.FastCrud.DapperExtensions.DeleteAsync[TEntity](IDbConnection connection, TEntity entityToDelete, Action`1 statementOptions)
	   at Infocaster.NOCNSF.Sportopleiders.Data.Repositories.GenericRepository`1.<Delete>d__7.MoveNext() in C:\\Infocaster Git\\NOC NSF\\Sportopleiders\\Website\\src\\Infocaster.Sportopleiders.Data\\Repositories\\GenericRepository.cs:line 62
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	   at Infocaster.NOCNSF.Sportopleiders.Data.Services.BedrijfService.<Delete>d__5.MoveNext() in C:\\Infocaster Git\\NOC NSF\\Sportopleiders\\Website\\src\\Infocaster.Sportopleiders.Data\\Services\\BedrijfService.cs:line 54
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	   at Infocaster.NOCNSF.Sportopleiders.WebApi.Controllers.BedrijfController.<Delete>d__5.MoveNext() in C:\\Infocaster Git\\NOC NSF\\Sportopleiders\\Website\\src\\Infocaster.Sportopleiders.WebApi\\Controllers\\BedrijfController.cs:line 49
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}
```

Is there a solution available?

**Comment by kipusoep** [comment]
Issue for me is fixed, I had:
```
await Db.DeleteAsync(GetById(id));
```

Changed it to:
```
var entity = await GetById(id);
await Db.DeleteAsync(entity);
```

**Comment by seLacheheb** [comment]
I'm facing the same issue when using synchronous `Insert `within an `async `method.
Using @kipusoep workaround (_ie_, use `await InsertAsync `instead of `Insert`) solved the problem.

**Comment by the-black-wolf** [comment]
In case anyone runs into this, the problem is in column discovery, if your class has all the properties as `internal set` instead of just `set` the default column mapper will ignore them all and the list of properties will be empty, leading to the empty sequence exception when statement generator tries to find out the largest order. 
Solution is to just have all the mappable properties as public `set`
